QT       += core gui multimedia multimediawidgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17 debug

# uncomment this to use asyncify
#wasm: QMAKE_LFLAGS += -s ASYNCIFY -Os

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

macos {
    PRODUCT_NAME = $$TARGET
    macx-xcode: PRODUCT_NAME = $${LITERAL_DOLLAR}{PRODUCT_NAME}
    INFOPLIST = \
       "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" \
       "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" \
       "<plist version=\"1.0\">" \
       "<dict>" \
        "    <key>CFBundleIconFile</key>" \
        "    <string></string>" \
        "    <key>CFBundlePackageType</key>" \
        "    <string>APPL</string>" \
        "    <key>CFBundleGetInfoString</key>" \
        "    <string>Created by Qt/QMake</string>" \
        "    <key>CFBundleSignature</key>" \
        "    <string>????</string>" \
        "    <key>CFBundleExecutable</key>" \
        "    <string>$$TARGET</string>" \
        "    <key>CFBundleIdentifier</key>" \
        "    <string>com.digia.$${LITERAL_DOLLAR}{PRODUCT_NAME:rfc1034identifier}</string>" \
        "    <key>CFBundleDisplayName</key>" \
        "    <string>$$PRODUCT_NAME</string>" \
        "    <key>CFBundleName</key>" \
        "    <string>$$PRODUCT_NAME</string>" \
        "    <key>CFBundleShortVersionString</key>" \
        "    <string>1.0</string>" \
        "    <key>CFBundleVersion</key>" \
        "    <string>1.0</string>" \
        "    <key>NSPrincipalClass</key>" \
        "    <string>NSApplication</string>" \
        "    <key>NSCameraUsageDescription</key>" \
        "    <string>Qt Multimedia Example</string>" \
        "    <key>NSMicrophoneUsageDescription</key>" \
        "    <string>Qt Multimedia Example</string>" \
        "    <key>NOTE</key>" \
        "    <string>This file was generated by Qt/QMake.</string>" \
        "</dict>" \
        "</plist>"
    write_file($$OUT_PWD/Info.plist, INFOPLIST)|error()
    QMAKE_INFO_PLIST = $$OUT_PWD/Info.plist
}
