qt_commandline_option(alsa TYPE boolean)
qt_commandline_option(evr TYPE boolean)
qt_commandline_option(wmf TYPE boolean)
qt_commandline_option(gstreamer TYPE optionalString VALUES no yes)
qt_commandline_option(pulseaudio TYPE boolean)
