# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.21
# 
# >> macros
# << macros

Name:       qt-mobility
Summary:    APIs for mobile device functionality
Version:    1.1.0+git2438
Release:    1
Group:      System/Libraries
License:    LGPLv2.1 with exception or GPLv3
URL:        http://qt.gitorious.org/qt-mobility
Source0:    http://get.qt.nokia.com/qt/add-ons/%{name}-opensource-src-%{version}.tar.gz
Source100:  qt-mobility.yaml
Requires:   libqtconnectivity1 = %{version}
Requires:   libqtcontacts1 = %{version}
Requires:   libqtfeedback1 = %{version}
Requires:   libqtgallery1 = %{version}
Requires:   libqtlocation1 = %{version}
Requires:   libqtmessaging1 = %{version}
Requires:   libqtmultimediakit1 = %{version}
Requires:   libqtorganizer1 = %{version}
Requires:   libqtpublishsubscribe1 = %{version}
Requires:   libqtsensors1 = %{version}
Requires:   libqtserviceframework1 = %{version}
Requires:   libqtsysteminfo1 = %{version}
Requires:   libqtversit1 = %{version}
Requires:   libqtversitorganizer1 = %{version}
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(blkid)
BuildRequires:  pkgconfig(bluez)
BuildRequires:  pkgconfig(connman)
BuildRequires:  pkgconfig(contextsubscriber-1.0)
BuildRequires:  pkgconfig(gconf-2.0)
BuildRequires:  pkgconfig(geoclue)
BuildRequires:  pkgconfig(gstreamer-plugins-bad-free-0.10)
BuildRequires:  pkgconfig(gstreamer-plugins-base-0.10)
BuildRequires:  pkgconfig(gypsy)
BuildRequires:  pkgconfig(libiphb)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(libmkcal)
BuildRequires:  pkgconfig(meegotouch)
BuildRequires:  pkgconfig(qttracker)
BuildRequires:  pkgconfig(qmfclient)
BuildRequires:  pkgconfig(sensord)
BuildRequires:  pkgconfig(udev)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(xrender)
BuildRequires:  pkgconfig(xv)
BuildRequires:  pkgconfig(QtSparql)
BuildRequires:  pkgconfig(QtSparqlTrackerExtensions)
BuildRequires:  qt-devel-tools
BuildRequires:  fdupes


%description
Qt Mobility delivers a set of new APIs for mobile device functionality. These
APIs allow the developer to use these features with ease from one framework and
apply them to phones, netbooks and non-mobile personal computers.



%package devel
Summary:    APIs for mobile device functionality - development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   servicefw

%description devel
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the development files needed to build Qt applications
using Qt Mobility libraries.


%package -n libqtconnectivity1
Summary:    Qt Mobility Connectivity module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtconnectivity1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Connectivity API. It provides APIs for working with
local devices.


%package -n libqtcontacts1
Summary:    Qt Mobility Contacts module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtcontacts1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains an API enabling clients to request contact data from
local or remote backends.


%package -n libqtfeedback1
Summary:    Qt Mobility Feedback module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtfeedback1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Feedback API. It enables a client to control
the vibration of the device or the piezo feedback from the screen.


%package -n libqtgallery1
Summary:    Qt Mobility Document Gallery module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtgallery1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains an API for accessing collections of documents and media
and their meta-data.


%package -n libqtlocation1
Summary:    Qt Mobility Location module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtlocation1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Location API. It provides a library for distributing
and receiving location data using arbitrary data sources.


%package -n libqtmessaging1
Summary:    Qt Mobility Messaging module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtmessaging1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Messaging API. It is a common interface for handling
SMS, MMS, MIME Email and TNEF Email messages.


%package -n libqtmultimediakit1
Summary:    Qt Mobility MultimediaKit module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtmultimediakit1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains a set of APIs to play and record media, and manage a
collection of media content.


%package -n libqtorganizer1
Summary:    Qt Mobility Organizer module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtorganizer1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains an API for management of calendar, scheduling and
personal data from local or remote backends. It includes the ability to create,
edit, list, delete and lookup organizer information whether it is stored
locally or remotely.


%package -n libqtpublishsubscribe1
Summary:    Qt Mobility Publish and Subscribe module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtpublishsubscribe1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Publish and Subscribe API (containing Value Space).
It enables applications to read item values, navigate through and subscribe to
change notifications.


%package -n libqtsensors1
Summary:    Qt Mobility Sensors module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libqtsql4-sqlite
Requires:   sensorfw
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtsensors1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Sensors API. It provides access to sensors.


%package -n libqtserviceframework1
Summary:    Qt Mobility Service Framework module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtserviceframework1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains a set of APIs to that allows clients to discover and
instantiate arbitrary services.


%package -n libqtsysteminfo1
Summary:    Qt Mobility System Information module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtsysteminfo1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains a set of APIs to discover system related information and
capabilities.


%package -n libqtversit1
Summary:    Qt Mobility Versit (vCard) module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtversit1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains an API to manage Versit documents, such as vCards.


%package -n libqtversitorganizer1
Summary:    Qt Mobility Versit (Organizer) module
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqtversitorganizer1
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains an API to manage Versit documents, such as iCalendar
documents. It interfaces the Organizer API and uses the same framework as for
vCards.


%package -n libdeclarative-contacts
Summary:    Qt Mobility Contacts QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-contacts
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Contacts QML plugin for QtDeclarative.


%package -n libdeclarative-feedback
Summary:    Qt Mobility Feedback QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-feedback
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Feedback QML plugin for QtDeclarative.


%package -n libdeclarative-gallery
Summary:    Qt Mobility Document Gallery QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-gallery
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Document Gallery QML plugin for QtDeclarative.


%package -n libdeclarative-location
Summary:    Qt Mobility Location QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-location
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Location QML plugin for QtDeclarative.


%package -n libdeclarative-messaging
Summary:    Qt Mobility Messaging QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-messaging
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Messaging QML plugin for QtDeclarative.


%package -n libdeclarative-multimedia
Summary:    Qt Mobility Multimedia QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-multimedia
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Multimedia QML plugin for QtDeclarative.


%package -n libdeclarative-organizer
Summary:    Qt Mobility Organizer QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-organizer
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Organizer QML plugin for QtDeclarative.


%package -n libdeclarative-publishsubscribe
Summary:    Qt Mobility Publish and Subscribe QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-publishsubscribe
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Publish and Subscribe QML plugin for QtDeclarative.


%package -n libdeclarative-sensors
Summary:    Qt Mobility Sensors Framework QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-sensors
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Sensors QML plugin for QtDeclarative.


%package -n libdeclarative-serviceframework
Summary:    Qt Mobility Service Framework QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-serviceframework
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Service Framework QML plugin for QtDeclarative.


%package -n libdeclarative-systeminfo
Summary:    Qt Mobility System Information QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-systeminfo
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the System Information QML plugin for QtDeclarative.


%package -n libdeclarative-connectivity
Summary:    Qt Mobility Connectivity QML plugin
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description -n libdeclarative-connectivity
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Connectivity QML plugin for QtDeclarative.


%package -n servicefw
Summary:    Qt Mobility Service Framework tool
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description -n servicefw
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains the Service Framework tool (servicefw). It allows
to register services and make them available over the Service Framework.


%package examples
Summary:    Qt Mobility examples
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description examples
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains Qt Mobility examples.


%package l10n
Summary:    APIs for mobile device functionality - localization files
Group:      System/I18n
Requires:   %{name} = %{version}-%{release}

%description l10n
Qt Mobility delivers a set of new APIs for mobile device functionality.

This package contains Qt Mobility translations.



%prep
%setup -q -n %{name}-opensource-src-%{version}

# >> setup
# << setup

%build
# >> build pre
# QMF environment variables should be set
export QMF_INCLUDEDIR=%{_includedir}/qmfclient
export QMF_LIBDIR=%{_libdir}
./configure \
-prefix "%{_prefix}" \
-headerdir "%{_includedir}" \
-libdir "%{_libdir}" \
-bindir "%{_bindir}" \
-plugindir "%{_libdir}/qt4/plugins" \
-demosdir "%{_libdir}/qtmobility/demos" \
-examplesdir "%{_libdir}/qtmobility/examples" \
-languages "ar cs da de es fr he hu ja pl pt ru sk sl sv zh_CN zh_TW" \
-examples \
-demos \
-modules "location contacts multimedia publishsubscribe versit messaging systeminfo serviceframework sensors gallery organizer feedback connectivity" \
-meego
make %{?_smp_mflags}
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%qmake_install
# Fix wrong path in pkgconfig files
find %{buildroot}%{_libdir}/pkgconfig -type f -name '*.pc' \
-exec perl -pi -e "s, -L%{_builddir}/%{name}-opensource-src-\Q%{version}\E/?\S+,,g" {} \;
# Fix executable permissions
find %{buildroot}%{_libdir}/qtmobility -type f -perm /u+x,g+x,o+x \( -false \
-o -name \*.qml \
-o -name \*.sci \
-o -name qmldir \
-o -name \*.txt \
\) -exec chmod -x \{\} +
# Fix duplicate files
%fdupes %{buildroot}%{_includedir}
%fdupes %{buildroot}%{_libdir}/qtmobility
# << install post
%fdupes  %{buildroot}/%{_datadir}/qtmobility/translations










%post -n libqtconnectivity1 -p /sbin/ldconfig

%postun -n libqtconnectivity1 -p /sbin/ldconfig


%post -n libqtcontacts1 -p /sbin/ldconfig

%postun -n libqtcontacts1 -p /sbin/ldconfig


%post -n libqtfeedback1 -p /sbin/ldconfig

%postun -n libqtfeedback1 -p /sbin/ldconfig


%post -n libqtgallery1 -p /sbin/ldconfig

%postun -n libqtgallery1 -p /sbin/ldconfig


%post -n libqtlocation1 -p /sbin/ldconfig

%postun -n libqtlocation1 -p /sbin/ldconfig


%post -n libqtmessaging1 -p /sbin/ldconfig

%postun -n libqtmessaging1 -p /sbin/ldconfig


%post -n libqtmultimediakit1 -p /sbin/ldconfig

%postun -n libqtmultimediakit1 -p /sbin/ldconfig


%post -n libqtorganizer1 -p /sbin/ldconfig

%postun -n libqtorganizer1 -p /sbin/ldconfig


%post -n libqtpublishsubscribe1 -p /sbin/ldconfig

%postun -n libqtpublishsubscribe1 -p /sbin/ldconfig


%post -n libqtsensors1 -p /sbin/ldconfig

%postun -n libqtsensors1 -p /sbin/ldconfig


%post -n libqtserviceframework1 -p /sbin/ldconfig

%postun -n libqtserviceframework1 -p /sbin/ldconfig


%post -n libqtsysteminfo1 -p /sbin/ldconfig

%postun -n libqtsysteminfo1 -p /sbin/ldconfig


%post -n libqtversit1 -p /sbin/ldconfig

%postun -n libqtversit1 -p /sbin/ldconfig


%post -n libqtversitorganizer1 -p /sbin/ldconfig

%postun -n libqtversitorganizer1 -p /sbin/ldconfig














































%files
%defattr(-,root,root,-)
# >> files
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_bindir}/icheck
%{_bindir}/ndefhandlergen
%{_bindir}/qcrmlgen
%{_bindir}/servicedbgen
%{_bindir}/servicexmlgen
%{_bindir}/vsexplorer
%{_includedir}/QtConnectivity/*.h
%{_includedir}/QtConnectivity/QBluetoothAddress
%{_includedir}/QtConnectivity/QBluetoothDeviceDiscoveryAgent
%{_includedir}/QtConnectivity/QBluetoothDeviceInfo
%{_includedir}/QtConnectivity/QBluetoothHostInfo
%{_includedir}/QtConnectivity/QBluetoothLocalDevice
%{_includedir}/QtConnectivity/QBluetoothServiceDiscoveryAgent
%{_includedir}/QtConnectivity/QBluetoothServiceInfo
%{_includedir}/QtConnectivity/QBluetoothSocket
%{_includedir}/QtConnectivity/QBluetoothTransferManager
%{_includedir}/QtConnectivity/QBluetoothTransferReply
%{_includedir}/QtConnectivity/QBluetoothTransferRequest
%{_includedir}/QtConnectivity/QBluetoothUuid
%{_includedir}/QtConnectivity/QDeclarativeNdefRecord
%{_includedir}/QtConnectivity/QL2capServer
%{_includedir}/QtConnectivity/QL2capSocket
%{_includedir}/QtConnectivity/QLlcpServer
%{_includedir}/QtConnectivity/QLlcpSocket
%{_includedir}/QtConnectivity/QNdefFilter
%{_includedir}/QtConnectivity/QNdefMessage
%{_includedir}/QtConnectivity/QNdefNfcTextRecord
%{_includedir}/QtConnectivity/QNdefNfcUriRecord
%{_includedir}/QtConnectivity/QNdefRecord
%{_includedir}/QtConnectivity/QNearFieldManager
%{_includedir}/QtConnectivity/QNearFieldTagType1
%{_includedir}/QtConnectivity/QNearFieldTagType2
%{_includedir}/QtConnectivity/QNearFieldTagType3
%{_includedir}/QtConnectivity/QNearFieldTagType4
%{_includedir}/QtConnectivity/QNearFieldTarget
%{_includedir}/QtConnectivity/QRfcommServer
%{_includedir}/QtConnectivity/QRfcommSocket
%{_includedir}/QtContacts/*.h
%{_includedir}/QtContacts/QContact
%{_includedir}/QtContacts/QContactAbstractRequest
%{_includedir}/QtContacts/QContactAction
%{_includedir}/QtContacts/QContactActionDescriptor
%{_includedir}/QtContacts/QContactActionFactory
%{_includedir}/QtContacts/QContactActionFilter
%{_includedir}/QtContacts/QContactActionTarget
%{_includedir}/QtContacts/QContactAddress
%{_includedir}/QtContacts/QContactAnniversary
%{_includedir}/QtContacts/QContactAvatar
%{_includedir}/QtContacts/QContactBirthday
%{_includedir}/QtContacts/QContactChangeLogFilter
%{_includedir}/QtContacts/QContactChangeSet
%{_includedir}/QtContacts/QContactDetail
%{_includedir}/QtContacts/QContactDetailDefinition
%{_includedir}/QtContacts/QContactDetailDefinitionFetchRequest
%{_includedir}/QtContacts/QContactDetailDefinitionRemoveRequest
%{_includedir}/QtContacts/QContactDetailDefinitionSaveRequest
%{_includedir}/QtContacts/QContactDetailFieldDefinition
%{_includedir}/QtContacts/QContactDetailFilter
%{_includedir}/QtContacts/QContactDetailRangeFilter
%{_includedir}/QtContacts/QContactDisplayLabel
%{_includedir}/QtContacts/QContactEmailAddress
%{_includedir}/QtContacts/QContactFamily
%{_includedir}/QtContacts/QContactFavorite
%{_includedir}/QtContacts/QContactFetchByIdRequest
%{_includedir}/QtContacts/QContactFetchHint
%{_includedir}/QtContacts/QContactFetchRequest
%{_includedir}/QtContacts/QContactFilter
%{_includedir}/QtContacts/QContactGender
%{_includedir}/QtContacts/QContactGeoLocation
%{_includedir}/QtContacts/QContactGlobalPresence
%{_includedir}/QtContacts/QContactGuid
%{_includedir}/QtContacts/QContactHobby
%{_includedir}/QtContacts/QContactId
%{_includedir}/QtContacts/QContactIntersectionFilter
%{_includedir}/QtContacts/QContactInvalidFilter
%{_includedir}/QtContacts/QContactLocalIdFetchRequest
%{_includedir}/QtContacts/QContactLocalIdFilter
%{_includedir}/QtContacts/QContactManager
%{_includedir}/QtContacts/QContactManagerEngine
%{_includedir}/QtContacts/QContactManagerEngineFactory
%{_includedir}/QtContacts/QContactManagerEngineV2
%{_includedir}/QtContacts/QContactName
%{_includedir}/QtContacts/QContactNickname
%{_includedir}/QtContacts/QContactNote
%{_includedir}/QtContacts/QContactObserver
%{_includedir}/QtContacts/QContactOnlineAccount
%{_includedir}/QtContacts/QContactOrganization
%{_includedir}/QtContacts/QContactPhoneNumber
%{_includedir}/QtContacts/QContactPresence
%{_includedir}/QtContacts/QContactRelationship
%{_includedir}/QtContacts/QContactRelationshipFetchRequest
%{_includedir}/QtContacts/QContactRelationshipFilter
%{_includedir}/QtContacts/QContactRelationshipRemoveRequest
%{_includedir}/QtContacts/QContactRelationshipSaveRequest
%{_includedir}/QtContacts/QContactRemoveRequest
%{_includedir}/QtContacts/QContactRingtone
%{_includedir}/QtContacts/QContactSaveRequest
%{_includedir}/QtContacts/QContactSortOrder
%{_includedir}/QtContacts/QContactSyncTarget
%{_includedir}/QtContacts/QContactTag
%{_includedir}/QtContacts/QContactThumbnail
%{_includedir}/QtContacts/QContactTimestamp
%{_includedir}/QtContacts/QContactType
%{_includedir}/QtContacts/QContactUnionFilter
%{_includedir}/QtContacts/QContactUrl
%{_includedir}/QtFeedback/*.h
%{_includedir}/QtFeedback/QFeedbackActuator
%{_includedir}/QtFeedback/QFeedbackEffect
%{_includedir}/QtFeedback/QFeedbackFileEffect
%{_includedir}/QtFeedback/QFeedbackFileInterface
%{_includedir}/QtFeedback/QFeedbackHapticsEffect
%{_includedir}/QtFeedback/QFeedbackHapticsInterface
%{_includedir}/QtFeedback/QFeedbackInterface
%{_includedir}/QtFeedback/QFeedbackThemeInterface
%{_includedir}/QtGallery/*.h
%{_includedir}/QtGallery/QAbstractGallery
%{_includedir}/QtGallery/QDocumentGallery
%{_includedir}/QtGallery/QGalleryAbstractRequest
%{_includedir}/QtGallery/QGalleryAbstractResponse
%{_includedir}/QtGallery/QGalleryFilter
%{_includedir}/QtGallery/QGalleryIntersectionFilter
%{_includedir}/QtGallery/QGalleryItemRequest
%{_includedir}/QtGallery/QGalleryMetaDataFilter
%{_includedir}/QtGallery/QGalleryQueryModel
%{_includedir}/QtGallery/QGalleryQueryRequest
%{_includedir}/QtGallery/QGalleryResource
%{_includedir}/QtGallery/QGalleryResultSet
%{_includedir}/QtGallery/QGalleryTypeRequest
%{_includedir}/QtGallery/QGalleryUnionFilter
%{_includedir}/QtLocation/*.h
%{_includedir}/QtLocation/QGeoAddress
%{_includedir}/QtLocation/QGeoAreaMonitor
%{_includedir}/QtLocation/QGeoBoundingArea
%{_includedir}/QtLocation/QGeoBoundingBox
%{_includedir}/QtLocation/QGeoBoundingCircle
%{_includedir}/QtLocation/QGeoCoordinate
%{_includedir}/QtLocation/QGeoManeuver
%{_includedir}/QtLocation/QGeoMapCircleObject
%{_includedir}/QtLocation/QGeoMapCustomObject
%{_includedir}/QtLocation/QGeoMapData
%{_includedir}/QtLocation/QGeoMapGroupObject
%{_includedir}/QtLocation/QGeoMapObject
%{_includedir}/QtLocation/QGeoMapObjectInfo
%{_includedir}/QtLocation/QGeoMapOverlay
%{_includedir}/QtLocation/QGeoMapPixmapObject
%{_includedir}/QtLocation/QGeoMapPolygonObject
%{_includedir}/QtLocation/QGeoMapPolylineObject
%{_includedir}/QtLocation/QGeoMapRectangleObject
%{_includedir}/QtLocation/QGeoMapRouteObject
%{_includedir}/QtLocation/QGeoMapTextObject
%{_includedir}/QtLocation/QGeoMappingManager
%{_includedir}/QtLocation/QGeoMappingManagerEngine
%{_includedir}/QtLocation/QGeoPlace
%{_includedir}/QtLocation/QGeoPositionInfo
%{_includedir}/QtLocation/QGeoPositionInfoSource
%{_includedir}/QtLocation/QGeoPositionInfoSourceFactory
%{_includedir}/QtLocation/QGeoRoute
%{_includedir}/QtLocation/QGeoRouteReply
%{_includedir}/QtLocation/QGeoRouteRequest
%{_includedir}/QtLocation/QGeoRouteSegment
%{_includedir}/QtLocation/QGeoRoutingManager
%{_includedir}/QtLocation/QGeoRoutingManagerEngine
%{_includedir}/QtLocation/QGeoSatelliteInfo
%{_includedir}/QtLocation/QGeoSatelliteInfoSource
%{_includedir}/QtLocation/QGeoSearchManager
%{_includedir}/QtLocation/QGeoSearchManagerEngine
%{_includedir}/QtLocation/QGeoSearchReply
%{_includedir}/QtLocation/QGeoServiceProvider
%{_includedir}/QtLocation/QGeoServiceProviderFactory
%{_includedir}/QtLocation/QGeoTiledMapData
%{_includedir}/QtLocation/QGeoTiledMapReply
%{_includedir}/QtLocation/QGeoTiledMapRequest
%{_includedir}/QtLocation/QGeoTiledMappingManagerEngine
%{_includedir}/QtLocation/QGraphicsGeoMap
%{_includedir}/QtLocation/QLandmark
%{_includedir}/QtLocation/QLandmarkAbstractRequest
%{_includedir}/QtLocation/QLandmarkAttributeFilter
%{_includedir}/QtLocation/QLandmarkBoxFilter
%{_includedir}/QtLocation/QLandmarkCategory
%{_includedir}/QtLocation/QLandmarkCategoryFetchByIdRequest
%{_includedir}/QtLocation/QLandmarkCategoryFetchRequest
%{_includedir}/QtLocation/QLandmarkCategoryFilter
%{_includedir}/QtLocation/QLandmarkCategoryId
%{_includedir}/QtLocation/QLandmarkCategoryIdFetchRequest
%{_includedir}/QtLocation/QLandmarkCategoryRemoveRequest
%{_includedir}/QtLocation/QLandmarkCategorySaveRequest
%{_includedir}/QtLocation/QLandmarkExportRequest
%{_includedir}/QtLocation/QLandmarkFetchByIdRequest
%{_includedir}/QtLocation/QLandmarkFetchRequest
%{_includedir}/QtLocation/QLandmarkFilter
%{_includedir}/QtLocation/QLandmarkId
%{_includedir}/QtLocation/QLandmarkIdFetchRequest
%{_includedir}/QtLocation/QLandmarkIdFilter
%{_includedir}/QtLocation/QLandmarkImportRequest
%{_includedir}/QtLocation/QLandmarkIntersectionFilter
%{_includedir}/QtLocation/QLandmarkManager
%{_includedir}/QtLocation/QLandmarkManagerEngine
%{_includedir}/QtLocation/QLandmarkManagerEngineFactory
%{_includedir}/QtLocation/QLandmarkNameFilter
%{_includedir}/QtLocation/QLandmarkNameSort
%{_includedir}/QtLocation/QLandmarkProximityFilter
%{_includedir}/QtLocation/QLandmarkRemoveRequest
%{_includedir}/QtLocation/QLandmarkSaveRequest
%{_includedir}/QtLocation/QLandmarkSortOrder
%{_includedir}/QtLocation/QLandmarkUnionFilter
%{_includedir}/QtLocation/QNmeaPositionInfoSource
%{_includedir}/QtMessaging/*.h
%{_includedir}/QtMessaging/QMessage
%{_includedir}/QtMessaging/QMessageAccount
%{_includedir}/QtMessaging/QMessageAccountFilter
%{_includedir}/QtMessaging/QMessageAccountId
%{_includedir}/QtMessaging/QMessageAccountSortOrder
%{_includedir}/QtMessaging/QMessageAddress
%{_includedir}/QtMessaging/QMessageContentContainer
%{_includedir}/QtMessaging/QMessageContentContainerId
%{_includedir}/QtMessaging/QMessageDataComparator
%{_includedir}/QtMessaging/QMessageFilter
%{_includedir}/QtMessaging/QMessageFolder
%{_includedir}/QtMessaging/QMessageFolderFilter
%{_includedir}/QtMessaging/QMessageFolderId
%{_includedir}/QtMessaging/QMessageFolderSortOrder
%{_includedir}/QtMessaging/QMessageId
%{_includedir}/QtMessaging/QMessageManager
%{_includedir}/QtMessaging/QMessageService
%{_includedir}/QtMessaging/QMessageSortOrder
%{_includedir}/QtMobility/*.h
%{_includedir}/QtMobility/QLatin1Constant
%{_includedir}/QtMultimediaKit/*.h
%{_includedir}/QtMultimediaKit/QAbstractAudioDeviceInfo
%{_includedir}/QtMultimediaKit/QAbstractAudioInput
%{_includedir}/QtMultimediaKit/QAbstractAudioOutput
%{_includedir}/QtMultimediaKit/QAbstractVideoBuffer
%{_includedir}/QtMultimediaKit/QAbstractVideoSurface
%{_includedir}/QtMultimediaKit/QAudio
%{_includedir}/QtMultimediaKit/QAudioCaptureSource
%{_includedir}/QtMultimediaKit/QAudioDeviceInfo
%{_includedir}/QtMultimediaKit/QAudioEncoderControl
%{_includedir}/QtMultimediaKit/QAudioEncoderSettings
%{_includedir}/QtMultimediaKit/QAudioEndpointSelector
%{_includedir}/QtMultimediaKit/QAudioFormat
%{_includedir}/QtMultimediaKit/QAudioInput
%{_includedir}/QtMultimediaKit/QAudioOutput
%{_includedir}/QtMultimediaKit/QAudioSystemPlugin
%{_includedir}/QtMultimediaKit/QCamera
%{_includedir}/QtMultimediaKit/QCameraControl
%{_includedir}/QtMultimediaKit/QCameraExposure
%{_includedir}/QtMultimediaKit/QCameraExposureControl
%{_includedir}/QtMultimediaKit/QCameraFlashControl
%{_includedir}/QtMultimediaKit/QCameraFocus
%{_includedir}/QtMultimediaKit/QCameraFocusControl
%{_includedir}/QtMultimediaKit/QCameraFocusZone
%{_includedir}/QtMultimediaKit/QCameraImageCapture
%{_includedir}/QtMultimediaKit/QCameraImageCaptureControl
%{_includedir}/QtMultimediaKit/QCameraImageProcessing
%{_includedir}/QtMultimediaKit/QCameraImageProcessingControl
%{_includedir}/QtMultimediaKit/QCameraCaptureBufferFormatControl
%{_includedir}/QtMultimediaKit/QCameraCaptureDestinationControl
%{_includedir}/QtMultimediaKit/QCameraLocksControl
%{_includedir}/QtMultimediaKit/QCameraViewfinder
%{_includedir}/QtMultimediaKit/QGraphicsVideoItem
%{_includedir}/QtMultimediaKit/QImageEncoderControl
%{_includedir}/QtMultimediaKit/QImageEncoderSettings
%{_includedir}/QtMultimediaKit/QLocalMediaPlaylistProvider
%{_includedir}/QtMultimediaKit/QMediaBindableInterface
%{_includedir}/QtMultimediaKit/QMediaContainerControl
%{_includedir}/QtMultimediaKit/QMediaContent
%{_includedir}/QtMultimediaKit/QMediaControl
%{_includedir}/QtMultimediaKit/QMediaImageViewer
%{_includedir}/QtMultimediaKit/QMediaObject
%{_includedir}/QtMultimediaKit/QMediaPlayer
%{_includedir}/QtMultimediaKit/QMediaPlayerControl
%{_includedir}/QtMultimediaKit/QMediaPlaylist
%{_includedir}/QtMultimediaKit/QMediaPlaylistControl
%{_includedir}/QtMultimediaKit/QMediaPlaylistIOPlugin
%{_includedir}/QtMultimediaKit/QMediaPlaylistNavigator
%{_includedir}/QtMultimediaKit/QMediaPlaylistProvider
%{_includedir}/QtMultimediaKit/QMediaPlaylistReader
%{_includedir}/QtMultimediaKit/QMediaPlaylistSourceControl
%{_includedir}/QtMultimediaKit/QMediaPlaylistWriter
%{_includedir}/QtMultimediaKit/QMediaRecorder
%{_includedir}/QtMultimediaKit/QMediaRecorderControl
%{_includedir}/QtMultimediaKit/QMediaResource
%{_includedir}/QtMultimediaKit/QMediaService
%{_includedir}/QtMultimediaKit/QMediaServiceProvider
%{_includedir}/QtMultimediaKit/QMediaServiceProviderHint
%{_includedir}/QtMultimediaKit/QMediaServiceProviderPlugin
%{_includedir}/QtMultimediaKit/QMediaStreamsControl
%{_includedir}/QtMultimediaKit/QMediaTimeInterval
%{_includedir}/QtMultimediaKit/QMediaTimeRange
%{_includedir}/QtMultimediaKit/QMetaDataReaderControl
%{_includedir}/QtMultimediaKit/QMetaDataWriterControl
%{_includedir}/QtMultimediaKit/QRadioTuner
%{_includedir}/QtMultimediaKit/QRadioTunerControl
%{_includedir}/QtMultimediaKit/QVideoDeviceControl
%{_includedir}/QtMultimediaKit/QVideoEncoderControl
%{_includedir}/QtMultimediaKit/QVideoEncoderSettings
%{_includedir}/QtMultimediaKit/QVideoFrame
%{_includedir}/QtMultimediaKit/QVideoRendererControl
%{_includedir}/QtMultimediaKit/QVideoSurfaceFormat
%{_includedir}/QtMultimediaKit/QVideoWidget
%{_includedir}/QtMultimediaKit/QVideoWidgetControl
%{_includedir}/QtMultimediaKit/QVideoWindowControl
%{_includedir}/QtMultimediaKit/QMediaNetworkAccessControl
%{_includedir}/QtOrganizer/*.h
%{_includedir}/QtOrganizer/QOrganizerAbstractRequest
%{_includedir}/QtOrganizer/QOrganizerCollection
%{_includedir}/QtOrganizer/QOrganizerCollectionChangeSet
%{_includedir}/QtOrganizer/QOrganizerCollectionEngineId
%{_includedir}/QtOrganizer/QOrganizerCollectionFetchRequest
%{_includedir}/QtOrganizer/QOrganizerCollectionId
%{_includedir}/QtOrganizer/QOrganizerCollectionRemoveRequest
%{_includedir}/QtOrganizer/QOrganizerCollectionSaveRequest
%{_includedir}/QtOrganizer/QOrganizerEvent
%{_includedir}/QtOrganizer/QOrganizerEventOccurrence
%{_includedir}/QtOrganizer/QOrganizerEventTime
%{_includedir}/QtOrganizer/QOrganizerItem
%{_includedir}/QtOrganizer/QOrganizerItemAudibleReminder
%{_includedir}/QtOrganizer/QOrganizerItemChangeLogFilter
%{_includedir}/QtOrganizer/QOrganizerItemChangeSet
%{_includedir}/QtOrganizer/QOrganizerItemCollectionFilter
%{_includedir}/QtOrganizer/QOrganizerItemComment
%{_includedir}/QtOrganizer/QOrganizerItemDescription
%{_includedir}/QtOrganizer/QOrganizerItemDetail
%{_includedir}/QtOrganizer/QOrganizerItemDetailDefinition
%{_includedir}/QtOrganizer/QOrganizerItemDetailDefinitionFetchRequest
%{_includedir}/QtOrganizer/QOrganizerItemDetailDefinitionRemoveRequest
%{_includedir}/QtOrganizer/QOrganizerItemDetailDefinitionSaveRequest
%{_includedir}/QtOrganizer/QOrganizerItemDetailFieldDefinition
%{_includedir}/QtOrganizer/QOrganizerItemDetailFilter
%{_includedir}/QtOrganizer/QOrganizerItemDetailRangeFilter
%{_includedir}/QtOrganizer/QOrganizerItemDisplayLabel
%{_includedir}/QtOrganizer/QOrganizerItemEmailReminder
%{_includedir}/QtOrganizer/QOrganizerItemEngineId
%{_includedir}/QtOrganizer/QOrganizerItemFetchByIdRequest
%{_includedir}/QtOrganizer/QOrganizerItemFetchForExportRequest
%{_includedir}/QtOrganizer/QOrganizerItemFetchHint
%{_includedir}/QtOrganizer/QOrganizerItemFetchRequest
%{_includedir}/QtOrganizer/QOrganizerItemFilter
%{_includedir}/QtOrganizer/QOrganizerItemGuid
%{_includedir}/QtOrganizer/QOrganizerItemId
%{_includedir}/QtOrganizer/QOrganizerItemIdFetchRequest
%{_includedir}/QtOrganizer/QOrganizerItemIdFilter
%{_includedir}/QtOrganizer/QOrganizerItemIntersectionFilter
%{_includedir}/QtOrganizer/QOrganizerItemInvalidFilter
%{_includedir}/QtOrganizer/QOrganizerItemLocation
%{_includedir}/QtOrganizer/QOrganizerItemObserver
%{_includedir}/QtOrganizer/QOrganizerItemOccurrenceFetchRequest
%{_includedir}/QtOrganizer/QOrganizerItemParent
%{_includedir}/QtOrganizer/QOrganizerItemPriority
%{_includedir}/QtOrganizer/QOrganizerItemRecurrence
%{_includedir}/QtOrganizer/QOrganizerItemReminder
%{_includedir}/QtOrganizer/QOrganizerItemRemoveRequest
%{_includedir}/QtOrganizer/QOrganizerItemSaveRequest
%{_includedir}/QtOrganizer/QOrganizerItemSortOrder
%{_includedir}/QtOrganizer/QOrganizerItemTag
%{_includedir}/QtOrganizer/QOrganizerItemTimestamp
%{_includedir}/QtOrganizer/QOrganizerItemType
%{_includedir}/QtOrganizer/QOrganizerItemUnionFilter
%{_includedir}/QtOrganizer/QOrganizerItemVisualReminder
%{_includedir}/QtOrganizer/QOrganizerJournal
%{_includedir}/QtOrganizer/QOrganizerJournalTime
%{_includedir}/QtOrganizer/QOrganizerManager
%{_includedir}/QtOrganizer/QOrganizerManagerEngine
%{_includedir}/QtOrganizer/QOrganizerManagerEngineFactory
%{_includedir}/QtOrganizer/QOrganizerManagerEngineV2
%{_includedir}/QtOrganizer/QOrganizerNote
%{_includedir}/QtOrganizer/QOrganizerRecurrenceRule
%{_includedir}/QtOrganizer/QOrganizerTodo
%{_includedir}/QtOrganizer/QOrganizerTodoOccurrence
%{_includedir}/QtOrganizer/QOrganizerTodoProgress
%{_includedir}/QtOrganizer/QOrganizerTodoTime
%{_includedir}/QtPublishSubscribe/*.h
%{_includedir}/QtPublishSubscribe/QValueSpace
%{_includedir}/QtPublishSubscribe/QValueSpacePublisher
%{_includedir}/QtPublishSubscribe/QValueSpaceSubscriber
%{_includedir}/QtSensors/*.h
%{_includedir}/QtSensors/QAccelerometer
%{_includedir}/QtSensors/QAccelerometerFilter
%{_includedir}/QtSensors/QAccelerometerReading
%{_includedir}/QtSensors/QAmbientLightFilter
%{_includedir}/QtSensors/QAmbientLightReading
%{_includedir}/QtSensors/QAmbientLightSensor
%{_includedir}/QtSensors/QCompass
%{_includedir}/QtSensors/QCompassFilter
%{_includedir}/QtSensors/QCompassReading
%{_includedir}/QtSensors/QGyroscope
%{_includedir}/QtSensors/QGyroscopeFilter
%{_includedir}/QtSensors/QGyroscopeReading
%{_includedir}/QtSensors/QLightFilter
%{_includedir}/QtSensors/QLightReading
%{_includedir}/QtSensors/QLightSensor
%{_includedir}/QtSensors/QMagnetometer
%{_includedir}/QtSensors/QMagnetometerFilter
%{_includedir}/QtSensors/QMagnetometerReading
%{_includedir}/QtSensors/QOrientationFilter
%{_includedir}/QtSensors/QOrientationReading
%{_includedir}/QtSensors/QOrientationSensor
%{_includedir}/QtSensors/QProximityFilter
%{_includedir}/QtSensors/QProximityReading
%{_includedir}/QtSensors/QProximitySensor
%{_includedir}/QtSensors/QRotationFilter
%{_includedir}/QtSensors/QRotationReading
%{_includedir}/QtSensors/QRotationSensor
%{_includedir}/QtSensors/QSensor
%{_includedir}/QtSensors/QSensorBackend
%{_includedir}/QtSensors/QSensorBackendFactory
%{_includedir}/QtSensors/QSensorChangesInterface
%{_includedir}/QtSensors/QSensorFilter
%{_includedir}/QtSensors/QSensorManager
%{_includedir}/QtSensors/QSensorPluginInterface
%{_includedir}/QtSensors/QSensorReading
%{_includedir}/QtSensors/QTapFilter
%{_includedir}/QtSensors/QTapReading
%{_includedir}/QtSensors/QTapSensor
%{_includedir}/QtServiceFramework/*.h
%{_includedir}/QtServiceFramework/QAbstractSecuritySession
%{_includedir}/QtServiceFramework/QRemoteServiceRegister
%{_includedir}/QtServiceFramework/QService
%{_includedir}/QtServiceFramework/QServiceContext
%{_includedir}/QtServiceFramework/QServiceFilter
%{_includedir}/QtServiceFramework/QServiceInterfaceDescriptor
%{_includedir}/QtServiceFramework/QServiceManager
%{_includedir}/QtServiceFramework/QServicePluginInterface
%{_includedir}/QtSystemInfo/*.h
%{_includedir}/QtSystemInfo/QSystemAlignedTimer
%{_includedir}/QtSystemInfo/QSystemBatteryInfo
%{_includedir}/QtSystemInfo/QSystemDeviceInfo
%{_includedir}/QtSystemInfo/QSystemDisplayInfo
%{_includedir}/QtSystemInfo/QSystemInfo
%{_includedir}/QtSystemInfo/QSystemNetworkInfo
%{_includedir}/QtSystemInfo/QSystemScreenSaver
%{_includedir}/QtSystemInfo/QSystemStorageInfo
%{_includedir}/QtVersit/*.h
%{_includedir}/QtVersit/QVersitContactExporter
%{_includedir}/QtVersit/QVersitContactExporterDetailHandler
%{_includedir}/QtVersit/QVersitContactExporterDetailHandlerV2
%{_includedir}/QtVersit/QVersitContactHandler
%{_includedir}/QtVersit/QVersitContactHandlerFactory
%{_includedir}/QtVersit/QVersitContactImporter
%{_includedir}/QtVersit/QVersitContactImporterPropertyHandler
%{_includedir}/QtVersit/QVersitContactImporterPropertyHandlerV2
%{_includedir}/QtVersit/QVersitDefaultResourceHandler
%{_includedir}/QtVersit/QVersitDocument
%{_includedir}/QtVersit/QVersitProperty
%{_includedir}/QtVersit/QVersitReader
%{_includedir}/QtVersit/QVersitResourceHandler
%{_includedir}/QtVersit/QVersitWriter
%{_includedir}/QtVersitOrganizer/*.h
%{_includedir}/QtVersitOrganizer/QVersitOrganizerExporter
%{_includedir}/QtVersitOrganizer/QVersitOrganizerExporterDetailHandler
%{_includedir}/QtVersitOrganizer/QVersitOrganizerHandler
%{_includedir}/QtVersitOrganizer/QVersitOrganizerHandlerFactory
%{_includedir}/QtVersitOrganizer/QVersitOrganizerImporter
%{_includedir}/QtVersitOrganizer/QVersitOrganizerImporterPropertyHandler
%{_includedir}/QtVersitOrganizer/QVersitTimeZoneHandler
%{_libdir}/libQtConnectivity.prl
%{_libdir}/libQtConnectivity.so
%{_libdir}/libQtContacts.prl
%{_libdir}/libQtContacts.so
%{_libdir}/libQtFeedback.prl
%{_libdir}/libQtFeedback.so
%{_libdir}/libQtGallery.prl
%{_libdir}/libQtGallery.so
%{_libdir}/libQtLocation.prl
%{_libdir}/libQtLocation.so
%{_libdir}/libQtMessaging.prl
%{_libdir}/libQtMessaging.so
%{_libdir}/libQtMultimediaKit.prl
%{_libdir}/libQtMultimediaKit.so
%{_libdir}/libQtOrganizer.prl
%{_libdir}/libQtOrganizer.so
%{_libdir}/libQtPublishSubscribe.prl
%{_libdir}/libQtPublishSubscribe.so
%{_libdir}/libQtSensors.prl
%{_libdir}/libQtSensors.so
%{_libdir}/libQtServiceFramework.prl
%{_libdir}/libQtServiceFramework.so
%{_libdir}/libQtSystemInfo.prl
%{_libdir}/libQtSystemInfo.so
%{_libdir}/libQtVersit.prl
%{_libdir}/libQtVersit.so
%{_libdir}/libQtVersitOrganizer.prl
%{_libdir}/libQtVersitOrganizer.so
%{_libdir}/pkgconfig/QtConnectivity.pc
%{_libdir}/pkgconfig/QtContacts.pc
%{_libdir}/pkgconfig/QtFeedback.pc
%{_libdir}/pkgconfig/QtGallery.pc
%{_libdir}/pkgconfig/QtLocation.pc
%{_libdir}/pkgconfig/QtMessaging.pc
%{_libdir}/pkgconfig/QtMultimediaKit.pc
%{_libdir}/pkgconfig/QtOrganizer.pc
%{_libdir}/pkgconfig/QtPublishSubscribe.pc
%{_libdir}/pkgconfig/QtSensors.pc
%{_libdir}/pkgconfig/QtServiceFramework.pc
%{_libdir}/pkgconfig/QtSystemInfo.pc
%{_libdir}/pkgconfig/QtVersit.pc
%{_libdir}/pkgconfig/QtVersitOrganizer.pc
%{_datadir}/qt4/mkspecs/features/mobility.prf
%{_datadir}/qt4/mkspecs/features/mobilityconfig.prf
# << files devel

%files -n libqtconnectivity1
%defattr(-,root,root,-)
# >> files libqtconnectivity1
%{_libdir}/libQtConnectivity.so.*
# << files libqtconnectivity1

%files -n libqtcontacts1
%defattr(-,root,root,-)
# >> files libqtcontacts1
%{_libdir}/libQtContacts.so.*
%{_libdir}/qt4/plugins/contacts/libqtcontacts_serviceactionmanager.so
# << files libqtcontacts1

%files -n libqtfeedback1
%defattr(-,root,root,-)
# >> files libqtfeedback1
%{_libdir}/libQtFeedback.so.*
%{_libdir}/qt4/plugins/feedback/libqtfeedback_meegotouch.so
%{_libdir}/qt4/plugins/feedback/libqtfeedback_mmk.so
# << files libqtfeedback1

%files -n libqtgallery1
%defattr(-,root,root,-)
# >> files libqtgallery1
%{_libdir}/libQtGallery.so.*
# << files libqtgallery1

%files -n libqtlocation1
%defattr(-,root,root,-)
# >> files libqtlocation1
%{_libdir}/libQtLocation.so.*
%{_libdir}/qt4/plugins/geoservices/libqtgeoservices_nokia.so
%{_libdir}/qt4/plugins/landmarks/libqtlandmarks_qsparql.so
# << files libqtlocation1

%files -n libqtmessaging1
%defattr(-,root,root,-)
# >> files libqtmessaging1
%{_libdir}/libQtMessaging.so.*
# << files libqtmessaging1

%files -n libqtmultimediakit1
%defattr(-,root,root,-)
# >> files libqtmultimediakit1
%{_libdir}/libQtMultimediaKit.so.*
%{_libdir}/qt4/plugins/mediaservice/libqgstengine.so
%{_libdir}/qt4/plugins/mediaservice/libqtmedia_v4lengine.so
%{_libdir}/qt4/plugins/playlistformats/libqtmultimediakit_m3u.so
%{_libdir}/qt4/plugins/audio/libqtmedia_pulse.so
# << files libqtmultimediakit1

%files -n libqtorganizer1
%defattr(-,root,root,-)
# >> files libqtorganizer1
%{_libdir}/libQtOrganizer.so.*
%{_libdir}/qt4/plugins/organizer/libqtorganizer_mkcal.so
# << files libqtorganizer1

%files -n libqtpublishsubscribe1
%defattr(-,root,root,-)
# >> files libqtpublishsubscribe1
%{_libdir}/libQtPublishSubscribe.so.*
# << files libqtpublishsubscribe1

%files -n libqtsensors1
%defattr(-,root,root,-)
# >> files libqtsensors1
%config %{_sysconfdir}/xdg/Nokia/Sensors.conf
%{_libdir}/libQtSensors.so.*
%{_libdir}/qt4/plugins/sensors/libqtsensors_generic.so
%{_libdir}/qt4/plugins/sensors/libqtsensors_meego.so
# << files libqtsensors1

%files -n libqtserviceframework1
%defattr(-,root,root,-)
# >> files libqtserviceframework1
%{_libdir}/libQtServiceFramework.so.*
# << files libqtserviceframework1

%files -n libqtsysteminfo1
%defattr(-,root,root,-)
# >> files libqtsysteminfo1
%{_libdir}/libQtSystemInfo.so.*
# << files libqtsysteminfo1

%files -n libqtversit1
%defattr(-,root,root,-)
# >> files libqtversit1
%{_libdir}/libQtVersit.so.*
%{_libdir}/qt4/plugins/versit/libqtversit_backuphandler.so
%{_libdir}/qt4/plugins/versit/libqtversit_vcardpreserver.so
# << files libqtversit1

%files -n libqtversitorganizer1
%defattr(-,root,root,-)
# >> files libqtversitorganizer1
%{_libdir}/libQtVersitOrganizer.so.*
# << files libqtversitorganizer1

%files -n libdeclarative-contacts
%defattr(-,root,root,-)
# >> files libdeclarative-contacts
%{_libdir}/qt4/imports/QtMobility/contacts/libdeclarative_contacts.so
%{_libdir}/qt4/imports/QtMobility/contacts/qmldir
# << files libdeclarative-contacts

%files -n libdeclarative-feedback
%defattr(-,root,root,-)
# >> files libdeclarative-feedback
%{_libdir}/qt4/imports/QtMobility/feedback/libdeclarative_feedback.so
%{_libdir}/qt4/imports/QtMobility/feedback/qmldir
# << files libdeclarative-feedback

%files -n libdeclarative-gallery
%defattr(-,root,root,-)
# >> files libdeclarative-gallery
%{_libdir}/qt4/imports/QtMobility/gallery/libdeclarative_gallery.so
%{_libdir}/qt4/imports/QtMobility/gallery/qmldir
# << files libdeclarative-gallery

%files -n libdeclarative-location
%defattr(-,root,root,-)
# >> files libdeclarative-location
%{_libdir}/qt4/imports/QtMobility/location/libdeclarative_location.so
%{_libdir}/qt4/imports/QtMobility/location/qmldir
# << files libdeclarative-location

%files -n libdeclarative-messaging
%defattr(-,root,root,-)
# >> files libdeclarative-messaging
%{_libdir}/qt4/imports/QtMobility/messaging/libdeclarative_messaging.so
%{_libdir}/qt4/imports/QtMobility/messaging/qmldir
# << files libdeclarative-messaging

%files -n libdeclarative-multimedia
%defattr(-,root,root,-)
# >> files libdeclarative-multimedia
%{_libdir}/qt4/imports/QtMultimediaKit/libdeclarative_multimedia.so
%{_libdir}/qt4/imports/QtMultimediaKit/qmldir
# << files libdeclarative-multimedia

%files -n libdeclarative-organizer
%defattr(-,root,root,-)
# >> files libdeclarative-organizer
%{_libdir}/qt4/imports/QtMobility/organizer/libdeclarative_organizer.so
%{_libdir}/qt4/imports/QtMobility/organizer/qmldir
# << files libdeclarative-organizer

%files -n libdeclarative-publishsubscribe
%defattr(-,root,root,-)
# >> files libdeclarative-publishsubscribe
%{_libdir}/qt4/imports/QtMobility/publishsubscribe/libdeclarative_publishsubscribe.so
%{_libdir}/qt4/imports/QtMobility/publishsubscribe/qmldir
# << files libdeclarative-publishsubscribe

%files -n libdeclarative-sensors
%defattr(-,root,root,-)
# >> files libdeclarative-sensors
%{_libdir}/qt4/imports/QtMobility/sensors/libdeclarative_sensors.so
%{_libdir}/qt4/imports/QtMobility/sensors/qmldir
# << files libdeclarative-sensors

%files -n libdeclarative-serviceframework
%defattr(-,root,root,-)
# >> files libdeclarative-serviceframework
%{_libdir}/qt4/imports/QtMobility/serviceframework/libdeclarative_serviceframework.so
%{_libdir}/qt4/imports/QtMobility/serviceframework/qmldir
# << files libdeclarative-serviceframework

%files -n libdeclarative-systeminfo
%defattr(-,root,root,-)
# >> files libdeclarative-systeminfo
%{_libdir}/qt4/imports/QtMobility/systeminfo/libdeclarative_systeminfo.so
%{_libdir}/qt4/imports/QtMobility/systeminfo/qmldir
# << files libdeclarative-systeminfo

%files -n libdeclarative-connectivity
%defattr(-,root,root,-)
# >> files libdeclarative-connectivity
%{_libdir}/qt4/imports/QtMobility/connectivity/libdeclarative_connectivity.so
%{_libdir}/qt4/imports/QtMobility/connectivity/qmldir
# << files libdeclarative-connectivity

%files -n servicefw
%defattr(-,root,root,-)
# >> files servicefw
%{_bindir}/servicefw
# << files servicefw

%files examples
%defattr(-,root,root,-)
# >> files examples
%{_libdir}/qt4/plugins/sensors/libqtsensors_grueplugin.so
%{_libdir}/qt4/plugins/serviceframework/libserviceframework_bluetoothtransferplugin.so
%{_libdir}/qt4/plugins/serviceframework/libserviceframework_filemanagerplugin.so
%{_libdir}/qt4/plugins/serviceframework/libserviceframework_landlinedialerservice.so
%{_libdir}/qt4/plugins/serviceframework/libserviceframework_notesmanagerplugin.so
%{_libdir}/qt4/plugins/serviceframework/libserviceframework_voipdialerservice.so
%{_libdir}/qtmobility/demos/
%{_libdir}/qtmobility/examples/
# << files examples

%files l10n
%defattr(-,root,root,-)
# >> files l10n
%{_datadir}/qtmobility/translations/qtmobility_ar.qm
%{_datadir}/qtmobility/translations/qtmobility_cs.qm
%{_datadir}/qtmobility/translations/qtmobility_da.qm
%{_datadir}/qtmobility/translations/qtmobility_de.qm
%{_datadir}/qtmobility/translations/qtmobility_es.qm
%{_datadir}/qtmobility/translations/qtmobility_fr.qm
%{_datadir}/qtmobility/translations/qtmobility_he.qm
%{_datadir}/qtmobility/translations/qtmobility_hu.qm
%{_datadir}/qtmobility/translations/qtmobility_ja.qm
%{_datadir}/qtmobility/translations/qtmobility_pl.qm
%{_datadir}/qtmobility/translations/qtmobility_pt.qm
%{_datadir}/qtmobility/translations/qtmobility_ru.qm
%{_datadir}/qtmobility/translations/qtmobility_sk.qm
%{_datadir}/qtmobility/translations/qtmobility_sl.qm
%{_datadir}/qtmobility/translations/qtmobility_sv.qm
#%{_datadir}/qtmobility/translations/qtmobility_uk.qm
%{_datadir}/qtmobility/translations/qtmobility_zh_CN.qm
%{_datadir}/qtmobility/translations/qtmobility_zh_TW.qm
# << files l10n

